### ISSUE TITLE
Klight 在HA升级到0.112后报错

### ISSUE THREAD

**Issue by cachenow** [jedmeng/homeassistant-konke#11]
**首先期待作者回归。**

**日志如下：**

日志详细信息（ ERROR ）
Logger: homeassistant.helpers.entity
Source: custom_components/konke/light.py:179
First occurred: 下午4:11:25 (25 occurrences)
Last logged: 下午4:23:46

Update for light.klight fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pykonkeio/device/klight.py", line 40, in update
    _, r, g, b, w, t, _ = m2.split('#')
ValueError: not enough values to unpack (expected 7, got 6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 272, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 463, in async_device_update
    await self.async_update()  # type: ignore
  File "/config/custom_components/konke/light.py", line 179, in async_update
    await self._device.update(type='light')
  File "/usr/local/lib/python3.7/site-packages/pykonkeio/device/klight.py", line 46, in update
    raise error.ErrorMessageFormat
pykonkeio.error.ErrorMessageFormat: Error: wrong message

**Comment by 1ban5599** [comment]
您好，按照您的教程安装小K插座成功，但在概览中找不到小K的图标，通知中出现如下提示：
Invalid config
The following integrations and platforms could not be set up:
switch.konke
Please check your config.

New devices discovered
We have discovered new devices on your network. Check it out
请问怎么解决？

**Comment by captainnx** [comment]
同样报错，有解决方案吗
